name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create additional environment variables
        run: |
          # get the repo name as lower case
          LGITHUB_REPOSITORY=${GITHUB_REPOSITORY,,}
          # remove 'docker-' from the repo name
          echo "DOCKER_REPOSITORY=${LGITHUB_REPOSITORY//docker-/}" >> $GITHUB_ENV
          # get the tag and remove prefix
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF//refs\/tags\//})" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and publish container
        uses: docker/build-push-action@v3
        with:
          build-args: RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:latest
            ${{ env.DOCKER_REPOSITORY }}:${{ env.RELEASE_VERSION }}
